mateapptimesheet/main/urls.py
from django.urls import path, include
from . import views
from timesheet.views import create_self_timesheet, self_timesheets

app_name = 'main'

urlpatterns = [
    path('', self_timesheets, name = 'Self_Timesheet'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('search/', views.search, name='Search'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapptimesheet/timesheet/urls.py
from django.urls import path, include, reverse
from . import views

app_name = 'timesheet'

# Customers

urlpatterns = [
    path('create_company/', views.create_company, name='Create_Company'),
    path('edit_company/<int:id>/', views.edit_company, name='Edit_Company'),
    path('delete_company/<int:id>/', views.delete_company, name='Delete_Company'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='Restore_Company'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='Full_Delete_Company'),
    path('companies/<int:a>/<int:b>/', views.companies , name='Companies'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company , name='Company'),
    path('company_notes/<int:id>/', views.companyNotes, name='Company_Notes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='Company_Notes_Title'),
    path('company_edit_notes/<int:id>/', views.companyNotesEdit, name='Company_Edit_Notes'),
]

# Projects

urlpatterns += [
    path('create_project/', views.create_project, name='Create_Project'),
    path('edit_project/<int:id>/', views.edit_project, name='Edit_Project'),
    path('delete_project/<int:id>/', views.delete_project, name='Delete_Project'),
    path('restore_project/<int:id>/<int:u>/', views.restore_project, name='Restore_Project'),
    path('full_delete_project/<int:id>/', views.full_delete_project, name='Full_Delete_Project'),
    path('projects/<int:a>/<int:b>/', views.projects , name='Projects'),
    path('project/<int:id>/<int:a>/<int:b>/', views.project , name='Project'),
    path('project_notes/<int:id>/', views.projectNotes, name='Project_Notes'),
    path('project_notes_title/<int:id>/', views.projectNotesTitle, name='Project_Notes_Title'),
    path('project_edit_notes/<int:id>/', views.projectNotesEdit, name='Project_Edit_Notes'),
]

# Timesheet

urlpatterns += [
    path('create_timesheet/', views.create_timesheet, name='Create_Timesheet'),
    path('create_self_timesheet/', views.create_self_timesheet, name='Create_Self_Timesheet'),
    path('edit_timesheet/<int:id>/', views.edit_timesheet, name='Edit_Timesheet'),
    path('edit_self_timesheet/<int:id>/', views.edit_self_timesheet, name='Edit_Self_Timesheet'),
    path('delete_timesheet_table/<int:id>/<int:u>/', views.delete_timesheet_table, name='Delete_Timesheet_Table'),
    path('delete_timesheet/<int:id>/<int:u>/', views.delete_timesheet, name='Delete_Timesheet'),
    path('restore_timesheet/<int:id>/<int:u>/', views.restore_timesheet, name='Restore_Timesheet'),
    path('full_delete_timesheet/<int:id>/', views.full_delete_timesheet, name='Full_Delete_Timesheet'),
    path('timesheets/<int:a>/<int:b>/', views.timesheets , name='Timesheets'),
    path('timesheets_self/<int:a>/<int:b>/', views.self_timesheets , name='Self_Timesheets'),
    path('timesheet/<int:id>/', views.timesheet , name='Timesheet'),
    path('timesheet_self/<int:id>/', views.timesheet_self , name='Timesheet_Self'),
    path('timesheet_notes/<int:id>/', views.timeNotes, name='Timesheet_Notes'),
    path('timesheet_notes_title/<int:id>/', views.timeNotesTitle, name='Timesheet_Notes_Title'),
    path('timesheet_edit_notes/<int:id>/', views.timeNotesEdit, name='Timesheet_Edit_Notes'),
]

# Users

urlpatterns += [
    path('users/<int:a>/<int:b>/', views.users, name='Users'),
    path('user/<int:id>/<int:a>/<int:b>/', views.user_detail, name='User'),
]


# urlpatterns += [
#     path('dev', views.dev_button, name='Dev'),
# ]

mateapptimesheet/timesheet/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, response, request, QueryDict
from django.template import loader
from django.contrib import messages
from .models import Address, Company, Project, Time
from .forms import CompanyForm, ProjectForm, TimesheetForm, FilterForm, TimeNotesForm, CompanyNotesForm, ProjectNotesForm
from .functions import timeSum, timesheetDateFilter, userAllocTime, getProjectList, getProjectTimesheets, checkProjectEmpty, getUserProjects
from main.forms import SearchForm
from main.functions import paginator
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from main.decorators import allowed_users
from django.contrib.auth import get_user_model
from django.db.models import Sum, Q
from django.contrib.postgres.search import SearchVector, SearchQuery




# CRUD Customer (Staff CUD)

# Customer List

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def companies(request, a, b):
    searchform = SearchForm
    if 'q' in request.GET:
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data['q']
            companies_list = Company.objects.filter(companyName__icontains=q, deleted=False)
            pgx = ''
            template = loader.get_template('timesheet/company_list.html')

    else:
        companies_list = Company.objects.order_by('companyName').filter(deleted=False) [a:b]
        length = Company.objects.filter(deleted=False).count()
        pgx = paginator(a, length, b)
        template = loader.get_template('timesheet/company_list.html')

    context = {
        'companies_list': companies_list,
        'searchform' : searchform,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))

# Customer View

@login_required
#@allowed_users(allowed_roles=['admin', 'staff'])
def company(request, id, a, b):
    company = Company.objects.get(id=id)
    project_dataset = getProjectList()
    project_list = project_dataset.filter(company_id=id).order_by('-projectStatus', 'projectName') [a:b]
    total_balance = project_dataset.filter(company_id=id).filter(Q(projectType='recurrent') | Q(projectStatus=False)).aggregate(Sum('balance'))
    length = Project.objects.filter(company_id=id).filter(deleted=False).count()
    pgx = paginator(a, length, b)
    template = loader.get_template('timesheet/company_view.html')
    context = {
        'company' : company,
        'project_list' : project_list,
        'total_balance' : total_balance,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))


# Customer Create

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def create_company(request):
    if request.method == 'POST':
        companyform = CompanyForm(request.POST)
        if companyform.is_valid():
            company = companyform.save()
            id = company.id
            return HttpResponseRedirect(f'/timesheet/company/{id}/0/5/')     

    else:
        companyform = CompanyForm()

    context = {
        'companyform': companyform,
        'title': _("New Customer")
    }
    return render(request, 'timesheet/company_create.html', context)

# Customer Update

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def edit_company(request, id):
    company = Company.objects.get(id=id)
    companyform = CompanyForm(request.POST or None, instance=company)
    if companyform.is_valid():
        companyform.save()
        return HttpResponseRedirect(f'/timesheet/company/{id}/0/5/')
    
    context = {
        'companyform': companyform,
        'company' : company,
    }
    return render(request, 'timesheet/company_create.html', context)

# Customer Delete

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def delete_company(request, id):
    uid = request.user.id
    company = Company.objects.get(id=id)
    company.deleted = 1
    company.deletedBy = uid
    company.save()
    return redirect('/timesheet/companies/0/10/')

# Customer Restore

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def restore_company(request, id, u):
    company = Company.objects.get(id=id)
    company.deleted = 0
    company.save()
    return HttpResponse(status = 200)

# Customer Full Delete

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def full_delete_company(request, id):
    company = Company.objects.get(id=id)
    company.deletedBy = None
    company.save()
    return HttpResponse(status = 200)

# CRUD Project (Staff CUD)

# Project List

@login_required
def projects(request, a, b):
    searchform = SearchForm
    if 'q' in request.GET:
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data['q']
            q = q.lower()
            status = True
            if '@inactive' in q:
                status = False
                q = q.replace('@inactive', '').strip()
                print(q, status)
            project_dataset = getProjectList()
            if q:
                project_list = project_dataset.annotate(search=SearchVector("projectName", "company__companyName")).filter(search=SearchQuery(q), projectStatus=status)
            else:
                project_list = project_dataset.filter(projectStatus=status)
            pgx = ''
            template = loader.get_template('timesheet/project_list.html')
    else:
        project_dataset = getProjectList().filter(projectStatus=True)
        project_list = project_dataset [a:b]
        length = project_dataset.count()
        pgx = paginator(a, length, b)
        template = loader.get_template('timesheet/project_list.html')

    context = {
        'project_list': project_list,
        'searchform' : searchform,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))

# Project View

@login_required
#@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def project(request, id, a, b):

    project = Project.objects.get(id=id)
    empty = checkProjectEmpty(id)

    if project.projectType == 'onetime':
        user_dataset = getProjectTimesheets('All', project.id)
        filterform = FilterForm(initial={'f':'All'})
        recurrent = False
    else:
        user_dataset = getProjectTimesheets('Current_Month', project.id)
        filterform = FilterForm(initial={'f':'Current_Month'})
        recurrent = True
    
    total_alloc_time = user_dataset.aggregate(Sum('alloc_time'))
    try:
        pending_time = project.budget - (total_alloc_time['alloc_time__sum'])
    except:
        pending_time = project.budget
    
    if 'q' in request.GET or 'f' in request.GET:
        filterform = FilterForm(request.GET)
        if filterform.is_valid():   
            f = filterform.cleaned_data['f']
            q = filterform.cleaned_data['q']
            user_list = getProjectTimesheets(f, project.id)
            if q:       
                user_list = user_list.annotate(search=SearchVector("last_name", "first_name")).filter(search=SearchQuery(q))
            pgx = ''
            template = loader.get_template('timesheet/project_view.html')
            view_total_alloc_time = user_list.aggregate(Sum('alloc_time'))           
    else:
        view_total_alloc_time = total_alloc_time
        user_list = user_dataset [a:b]
        length = user_dataset.count()
        pgx = paginator(a, length, b)
        template = loader.get_template('timesheet/project_view.html')
        
    context = {
        'project' : project,
        'user_list' : user_list,
        'filterform' : filterform,
        'total_alloc_time' : view_total_alloc_time,
        'pending_time' : pending_time,
        'recurrent' : recurrent,
        'empty' : empty,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))

# Project Create

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def create_project(request):
    if request.method == 'POST':
        projectform = ProjectForm(request.POST)
        if projectform.is_valid():
            project = projectform.save()
            id = project.id
            return HttpResponseRedirect(f'/timesheet/project/{id}/0/5/')     

    else:
        projectform = ProjectForm()

    context = {
        'projectform': projectform,
        'title': _("New Project")
    }
    return render(request, 'timesheet/project_create.html', context)

# Project Update

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def edit_project(request, id):
    project = Project.objects.get(id=id)
    projectform = ProjectForm(request.POST or None, instance=project)
    if projectform.is_valid():
        projectform.save()
        return HttpResponseRedirect(f'/timesheet/project/{id}/0/5/')
    
    context = {
        'projectform': projectform,
        'project' : project,
    }
    return render(request, 'timesheet/project_create.html', context)

# Project Delete

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def delete_project(request, id):
    uid = request.user.id
    project = Project.objects.get(id=id)
    project.deleted = 1
    project.deletedBy = uid
    project.save()
    return redirect('/timesheet/projects/0/10/')

# Project Restore

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def restore_project(request, id, u):
    project = Project.objects.get(id=id)
    project.deleted = 0
    project.save()
    return HttpResponse(status = 200)

# Project Full Delete

@login_required
@allowed_users(allowed_roles=['admin', 'staff', 'supervisor'])
def full_delete_project(request, id):
    project = Project.objects.get(id=id)
    project.deletedBy = None
    project.save()
    return HttpResponse(status = 200)

mateapptimesheet/templates/timesheet/partials/company_edit_notes.html
{% load i18n %} 

<form hx-put="{% url 'timesheet:Company_Edit_Notes' id=company.id %}" hx-target="#notes" hx-swap="outerHTML swap:0.2s" id="notes">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{notesform.companyNotes}}
        <label for="id_notes">{% trans "Notes:" %}</label>
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'timesheet:Company_Notes_Title' id=company.id %}" hx-target="#notes">{% trans "Cancel" %}</button>

</form>

mateapptimesheet/templates/timesheet/partials/company_notes.html
{% load i18n %}

<div class="row py-3 justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col p-3 col-lg-10 hx-pointer" hx-get="{% url 'timesheet:Company_Notes_Title' id=company.id %}">
        {{company.companyNotes|linebreaks}}<span><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
    </div>
</div>

mateapptimesheet/templates/timesheet/partials/company_notes_title.html
{% load i18n %}

<div class="row justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col py-3 mb-3 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'timesheet:Company_Edit_Notes' id=company.id %}"></i></span>{{ company.companyNotesTitle }} 
        <span class="hx-pointer" hx-get="{% url 'timesheet:Company_Notes' id=company.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>

mateapptimesheet/templates/timesheet/partials/project_edit_notes.html
{% load i18n %} 

<form hx-put="{% url 'timesheet:Project_Edit_Notes' id=project.id %}" hx-target="#notes" hx-swap="outerHTML swap:0.2s" id="notes">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{notesform.projectNotes}}
        <label for="id_notes">{% trans "Notes:" %}</label>
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'timesheet:Project_Notes_Title' id=project.id %}" hx-target="#notes">{% trans "Cancel" %}</button>

</form>

mateapptimesheet/templates/timesheet/partials/project_notes.html
{% load i18n %}

<div class="row py-3 justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col p-3 col-lg-10 hx-pointer" hx-get="{% url 'timesheet:Project_Notes_Title' id=project.id %}">
        {{project.projectNotes|linebreaks}}<span><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
    </div>
</div>

mateapptimesheet/templates/timesheet/partials/project_notes_title.html
{% load i18n %}

<div class="row justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col py-3 mb-3 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'timesheet:Project_Edit_Notes' id=project.id %}"></i></span>{{ project.projectNotesTitle }} 
        <span class="hx-pointer" hx-get="{% url 'timesheet:Project_Notes' id=project.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>

mateapptimesheet/templates/timesheet/partials/timesheet_edit_notes.html
{% load i18n %} 

<form hx-put="{% url 'timesheet:Timesheet_Edit_Notes' id=timesheet.id %}" hx-target="#notes" hx-swap="outerHTML swap:0.2s" id="notes">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{notesform.timeNotes}}
        <label for="id_notes">{% trans "Notes:" %}</label>
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'timesheet:Timesheet_Notes_Title' id=timesheet.id %}" hx-target="#notes">{% trans "Cancel" %}</button>

</form>

mateapptimesheet/templates/timesheet/partials/timesheet_notes.html
{% load i18n %}

<div class="row py-3 justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col p-3 col-lg-10 hx-pointer" hx-get="{% url 'timesheet:Timesheet_Notes_Title' id=timesheet.id %}">
        {{timesheet.timeNotes|linebreaks}}<span><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
    </div>
</div>

mateapptimesheet/templates/timesheet/partials/timesheet_notes_title.html
{% load i18n %}

<div class="row justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col py-3 mb-3 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'timesheet:Timesheet_Edit_Notes' id=timesheet.id %}"></i></span>{{ timesheet.timeNotesTitle }} 
        <span class="hx-pointer" hx-get="{% url 'timesheet:Timesheet_Notes' id=timesheet.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>