mateapptimesheet/main/urls.py
from django.urls import path, include
from . import views
from timesheet.views import create_self_timesheet, self_timesheets

app_name = 'main'

urlpatterns = [
    path('', self_timesheets, name = 'Self_Timesheet'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('search/', views.search, name='Search'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapptimesheet/timesheet/urls.py
from django.urls import path, include, reverse
from . import views

app_name = 'timesheet'

# Customers

urlpatterns = [
    path('create_company/', views.create_company, name='Create_Company'),
    path('edit_company/<int:id>/', views.edit_company, name='Edit_Company'),
    path('delete_company/<int:id>/', views.delete_company, name='Delete_Company'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='Restore_Company'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='Full_Delete_Company'),
    path('companies/<int:a>/<int:b>/', views.companies , name='Companies'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company , name='Company'),
    path('company_notes/<int:id>/', views.companyNotes, name='Company_Notes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='Company_Notes_Title'),
    path('company_edit_notes/<int:id>/', views.companyNotesEdit, name='Company_Edit_Notes'),
]

# Projects

urlpatterns += [
    path('create_project/', views.create_project, name='Create_Project'),
    path('edit_project/<int:id>/', views.edit_project, name='Edit_Project'),
    path('delete_project/<int:id>/', views.delete_project, name='Delete_Project'),
    path('restore_project/<int:id>/<int:u>/', views.restore_project, name='Restore_Project'),
    path('full_delete_project/<int:id>/', views.full_delete_project, name='Full_Delete_Project'),
    path('projects/<int:a>/<int:b>/', views.projects , name='Projects'),
    path('project/<int:id>/<int:a>/<int:b>/', views.project , name='Project'),
    path('project_notes/<int:id>/', views.projectNotes, name='Project_Notes'),
    path('project_notes_title/<int:id>/', views.projectNotesTitle, name='Project_Notes_Title'),
    path('project_edit_notes/<int:id>/', views.projectNotesEdit, name='Project_Edit_Notes'),
]

# Timesheet

urlpatterns += [
    path('create_timesheet/', views.create_timesheet, name='Create_Timesheet'),
    path('create_self_timesheet/', views.create_self_timesheet, name='Create_Self_Timesheet'),
    path('edit_timesheet/<int:id>/', views.edit_timesheet, name='Edit_Timesheet'),
    path('edit_self_timesheet/<int:id>/', views.edit_self_timesheet, name='Edit_Self_Timesheet'),
    path('delete_timesheet_table/<int:id>/<int:u>/', views.delete_timesheet_table, name='Delete_Timesheet_Table'),
    path('delete_timesheet/<int:id>/<int:u>/', views.delete_timesheet, name='Delete_Timesheet'),
    path('restore_timesheet/<int:id>/<int:u>/', views.restore_timesheet, name='Restore_Timesheet'),
    path('full_delete_timesheet/<int:id>/', views.full_delete_timesheet, name='Full_Delete_Timesheet'),
    path('timesheets/<int:a>/<int:b>/', views.timesheets , name='Timesheets'),
    path('timesheets_self/<int:a>/<int:b>/', views.self_timesheets , name='Self_Timesheets'),
    path('timesheet/<int:id>/', views.timesheet , name='Timesheet'),
    path('timesheet_self/<int:id>/', views.timesheet_self , name='Timesheet_Self'),
    path('timesheet_notes/<int:id>/', views.timeNotes, name='Timesheet_Notes'),
    path('timesheet_notes_title/<int:id>/', views.timeNotesTitle, name='Timesheet_Notes_Title'),
    path('timesheet_edit_notes/<int:id>/', views.timeNotesEdit, name='Timesheet_Edit_Notes'),
]

# Users

urlpatterns += [
    path('users/<int:a>/<int:b>/', views.users, name='Users'),
    path('user/<int:id>/<int:a>/<int:b>/', views.user_detail, name='User'),
]


# urlpatterns += [
#     path('dev', views.dev_button, name='Dev'),
# ]

mateapptimesheet/main/models.py
from django.db import models

# Create your models here.

mateapptimesheet/main/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class SearchForm(forms.Form):
    q = forms.CharField(
        label="Search",
        required=False,
        widget=forms.TextInput(attrs={'class':'form-control me-2 q', 'placeholder':_('Search:'), 'type':'search', 'aria-label':'search'}),
    )

mateapptimesheet/main/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, response, request
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout, authenticate, get_user_model
from .decorators import user_not_authenticated, allowed_users
from .forms import SearchForm
from timesheet.models import Company, Project, Time
from django.contrib.auth.decorators import login_required
from itertools import chain
from operator import attrgetter
from django.contrib.postgres.search import TrigramSimilarity, SearchVector, SearchQuery
from django.utils.translation import gettext_lazy as _
from .functions import paginator
from django.template import loader
from django.core.management import call_command

# Create your views here.

def home(request):
    return render(request,'main/home.html')

# Login

@user_not_authenticated
def login(request):
    if request.method == 'GET':
        return render(request, 'main/login.html', {'form' : AuthenticationForm})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, _('Incorrect Username or Password.'))
            return render(request, 'main/login.html', {
                'form' : AuthenticationForm,
                'error' : _('Incorrect Username or Password.')
                })
        else:
            auth_login(request, user)
            return redirect('../timesheet/timesheets_self/0/10/')

# Logout

def signout(request):
    logout(request)
    return redirect('/login/')

# Search

@login_required
def search(request):
    pass
    '''
    searchform = SearchForm
    results = ''

    if 'q' in request.GET:
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data['q']
            ln_results = Person.objects.annotate(similarity=TrigramSimilarity('lastName', q),).filter(similarity__gte=0.3, deleted=False).order_by('-similarity')
            fn_results = Person.objects.annotate(similarity=TrigramSimilarity('firstName', q),).filter(similarity__gte=0.5, deleted=False).order_by('-similarity')
            pp_results = Person.objects.annotate(similarity=TrigramSimilarity('position', q),).filter(similarity__gte=0.5, deleted=False).order_by('-similarity')
            c_results = Company.objects.annotate(similarity=TrigramSimilarity('companyName', q),).filter(similarity__gte=0.3, deleted=False).order_by('-similarity')
            ct_results = Company.objects.annotate(similarity=TrigramSimilarity('tax_id', q),).filter(similarity__gte=0.6, deleted=False).order_by('-similarity')
            results = sorted(chain(ln_results, fn_results, c_results, pp_results, ct_results),
                             key=attrgetter('similarity'),
                             reverse=True,
                             )
            if results == []:
                print('no results')
                messages.warning(request, _("The search didn't return any result."))

    context = {
        'searchform' : searchform,
        'results' : results,
    }

    return render(request, 'main/home.html', context)

'''

# User Trash

@login_required
def user_trash(request, a, b):
    uid = request.user.id
    deleted_companies_list = Company.objects.filter(deleted=True, deletedBy=uid)
    deleted_projects_list = Project.objects.filter(deleted=True, deletedBy=uid)
    deleted_timesheets_list = Time.objects.filter(deleted=True, deletedBy=uid)
    trash = sorted(chain(deleted_projects_list, deleted_companies_list, deleted_timesheets_list),
                    key=attrgetter('modified_date'),
                    reverse=True,
                    )
    trash_list = trash [a:b]
    length = len(trash)
    pgx = paginator(a, length, b)
    template = loader.get_template('main/user_trash.html')
    context = {
        'trash_list': trash_list,
        'pgx' : pgx
    }
    return HttpResponse(template.render(context, request))

# Admin Trash

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def admin_trash(request, a, b):
    searchform = SearchForm
    if 'q' in request.GET:
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            q = searchform.cleaned_data['q']
            deleted_companies_list = Company.objects.filter(deleted=True).annotate(search=SearchVector("companyName", "tax_id")).filter(search=SearchQuery(q))
            deleted_projects_list = Project.objects.filter(deleted=True).annotate(search=SearchVector("projectName", "company__companyName")).filter(search=SearchQuery(q))
            deleted_timesheets_list = Time.objects.filter(deleted=True).annotate(search=SearchVector("user__last_name", "user__first_name", "timeDate", "project__projectName", "project__company__companyName")).filter(search=SearchQuery(q))
            trash_list = list(chain(deleted_companies_list, deleted_projects_list, deleted_timesheets_list))
            pgx =  ''
            template = loader.get_template('main/admin_trash.html')
            if trash_list == []:
                messages.warning(request, _("The search didn't return any result."))
    else:
        deleted_companies_list = Company.objects.filter(deleted=True)
        deleted_projects_list = Project.objects.filter(deleted=True)
        deleted_timesheets_list = Time.objects.filter(deleted=True)
        trash = sorted(chain(deleted_companies_list, deleted_projects_list, deleted_timesheets_list),
                        key=attrgetter('modified_date'),
                        reverse=True,
                        )
        trash_list = trash [a:b]
        length = len(trash)
        pgx = paginator(a, length, b)
        template = loader.get_template('main/admin_trash.html')
    
    context = {
        'searchform' : searchform,
        'trash_list': trash_list,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))

# Admin Home (Admin)

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def admin_home(request, a=0, b=10):
    # Backup files List
    folder = f'{settings.MEDIA_ROOT}/backup/'
    file_list = os.listdir(folder)
    file_list = sorted(file_list, reverse=True)
    path = f'{settings.MEDIA_URL}backup/'
    template = loader.get_template('main/admin_home.html')
    context = {
        'file_list': file_list,
        'path': path,
    }
    return HttpResponse(template.render(context, request))

# Efectúa un backup manualmente

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def do_backup(request):
    call_command('dbbackup', clean=True, interactive=False)
    return redirect('/admin_home/0/10/')

mateapptimesheet/templates/main/admin_home.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/admin_navbar.html' %}
{% endblock navbar %}

{% block content %}

<!-- Backup Module -->
<div class="row mt-3 mx-1 justify-content-md-center">
  <div class="col bg-white p-2 col-lg-10 rounded border ">
        <div class="container-fluid px-4">
         <h4><i class="bi bi-hdd-stack"></i>&nbsp;{% trans "Backups" %}</h4>
        </div>
  </div>
  
</div>
<div class="row mt-3 mx-1 justify-content-md-center">
  <div class="col bg-white p-3 border rounded col-lg-10">
  {% if file_list %}
  <div class="table-responsive">
  <table class="table table-hover" id="backup_list" name="Backup_List">
      <!-- Cabecera de Tabla -->
      <thead class="table-secondary">
          <th>{% trans "Name" %}</th>
      </thead>

      <!-- Cuerpo de Tabla -->

      <tbody>
          {% for file in file_list %}
          <tr>
            {% if not '.gitignore' in file %}  
            <td><a class="nav-link" href="{{ path }}{{ file }}" download>{{ file }}</a></td>
            {% endif %}
          </tr>
          {% endfor %}
      </tbody>

  </table>
  </div>
  {% else %}
      <p>{% trans "No backups available." %}</p>
  {% endif %}
  </div>
</div>
{% endblock %}

mateapptimesheet/templates/main/admin_trash.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/admin_navbar.html' %}
{% endblock navbar %}

{% block content %}

<div class="row mt-3 mx-1 justify-content-md-center">
    <div class="col bg-white p-2 col-lg-10 rounded border ">
      <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid px-4">
          <a class="navbar-brand" href=""><h4><i class="bi bi-trash"></i>&nbsp;{% trans "System Trash" %}</h4></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#trashNavbar" aria-controls="trashNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="trashNavbar">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <div>
            <form class="d-flex" role="search">
                {{searchform.q}}
                <button class="btn btn-outline-success mx-2" type="submit">{% trans "Search" %}</button>
              </form>
            </div>
              <div><a href="/admin_trash/0/10/" class="btn btn-outline-secondary my-2">{% trans "Clear" %}</a></div>
          </div>
        </div>
      </nav>
    </div>
</div> 
<div class="row mt-3 mx-1 justify-content-md-center" id="companies-table-block">
    
  <div class="col bg-white p-3 border rounded col-lg-10">
    {% if trash_list %}
    <div class="table-responsive">
    <table class="table table-hover" id="trash_list" name="Trash_List">

    <!-- Cuerpo de Tabla -->
    
    <tbody hx-target="closest tr" hx-swap="outerHTML swap:0.5s">
        {% for trash in trash_list %}
        <tr>
            <td>
              {{ trash }}
            </td>
            <td>
              {% if trash.companyName %}
                <div>{% trans "Company" %}</div>
              {% elif trash.projectName%}
                <div>{% trans "Project" %}</div>
              {% else %}
                <div>{% trans "Timesheet" %}</div>
              {% endif %}
            </td>
            <td>
              {% if trash.companyName %}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Company' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% elif trash.projectName%}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Project' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% else %}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Timesheet' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
      {% if pgx.pgs > 1 %}
      <nav aria-label="Page navigation" class="m-3">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="/admin_trash/{{pgx.idxpl}}/{{.pgx.idxpr}}/" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% for link in pgx.lks %}
          <li class="page-item"><a class="page-link" id="page-link" href="/admin_trash/{{link.pl}}/{{link.pr}}/">{{link.page}}</a></li>
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="/admin_trash/{{pgx.idxnl}}/{{.pgxidxnr}}/" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
      {% endif %}

    {% else %}
        <p>{% trans "Trash is empty." %}</p>
    {% endif %}
    </div>
</div>
{% endblock %}

mateapptimesheet/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>MateApp Timesheet</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'main/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body class="bg-light">
    {% block navbar %}
    {% endblock %}
 
    <br>
    <div class="container-sm" id="messaging" name="messaging">
        {% include 'includes/messaging.html' %}
    </div>

    <div class="container-fluid" id="block-content" name="block-content">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'includes/footer.html' %}

    <script src="{% static 'main/js/paginator_helper.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'main/js/htmx.min.js' %}"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>

</body>
</html>

mateapptimesheet/templates/main/home.html
{% extends 'main/base.html' %}

{% load static %}
{% load i18n %}


{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<div class="row row-col-1 py-3 justify-content-center">
    <div class="col bg-white m-5 p-4 border col-lg-5 rounded">
        <div style="text-align: center">
        <h2>MateApp Timesheet</h2>
        <br>
        </div>
        <form method="GET">
            <div class="d-flex">
                {{searchform.q}}
            </div>
            <br>
            <button type="submit" class="w-100 btn btn-lg-5 btn-outline-success">{% trans "Search" %}</button>
        </form>
       
        {% for result in results %}
        <div class="col my-3 bg-white p-4 border rounded">
        {% if result.lastName %}
        <strong><a class="nav-link" href="/directory/person/{{ result.id }}/">{{ result }}</a></strong>
        <p>{{ result.celphone }}</p>
        {% else %}
        <strong><a class="nav-link" href="/directory/company/{{ result.id }}/0/5/">{{ result }}</a></strong>
        <p>{{ result.tax_id }} </p>
        {% endif %}
        </div>
        {% endfor %}
        
    </div>
</div>
<script src="{% static 'main/js/search_helper.js' %}"></script>
{% endblock content %}

mateapptimesheet/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<form method="POST" autocomplete="off">

{% csrf_token %}
{% comment %} <div class="row row-col-1 py-3 justify-content-center"> {% endcomment %}
    {% comment %} <div class="col bg-white m-5 p-4 border col-lg-5 rounded"> {% endcomment %}

<div class="row py-3 justify-content-center">
    <div class="col col-lg-4 bg-white m-5 p-4 border rounded">
        <div style="text-align: center;">
        <div class="display-6">MateApp Timesheet</div>
        <br>
        </div>
            <div class="form-floating">
                {{form.username}}
                <label for="Username" class="form-label">{% trans "Username:" %}</label>
            </div>
            <br>
            <div class="form-floating">
                {{form.password}}
                <label for="Password" class="form-label">{% trans "Password:" %}</label>
            </div>
            <br>
        <button type="submit" class="w-100 btn btn-lg-5 btn-outline-success">Login</button>
        <div>
            <br>
            <a class="nav-link" href="/users/password_reset/">{% trans "Forgot Password?" %}</a>
            <br>
        </div>
    </div>
</div>
<script src="{% static 'main/js/login.js' %}"></script>
{% endblock %}

mateapptimesheet/templates/main/user_trash.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}
<div class="row mt-3 mx-1 justify-content-md-center">
    <div class="col bg-white p-2 col-lg-10 rounded border ">
      <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid px-4">
          <a class="navbar-brand" href="#"><h2>{% trans "Trash" %}</h2></a>
        </div>
      </nav>
    </div>
</div> 
<div class="row mt-3 mx-1 justify-content-md-center" id="companies-table-block">
    <div class="col bg-white p-3 border rounded col-lg-10">
    {% if trash_list %}
    <div class="table-responsive">
    <table class="table table-hover" id="trash_list" name="Trash_List">

    <!-- Cuerpo de Tabla -->
    
    <tbody hx-target="closest tr" hx-swap="outerHTML swap:0.5s">
        {% for trash in trash_list %}
        <tr>
            <td>
              <p>{{ trash }}</p>
            </td>
            <td>
              {% if trash.companyName %}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Company' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% elif trash.projectName%}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Project' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% else %}
                <div class="btn btn-outline-success btn-sm" hx-delete={% url 'timesheet:Restore_Timesheet' id=trash.id u=0 %}>{% trans "Restore" %}</div>
              {% endif %}
            </td>
            <td>
              {% if trash.companyName %}
                <div class="btn btn-outline-danger btn-sm" hx-delete={% url 'timesheet:Full_Delete_Company' id=trash.id %}>{% trans "Delete" %}</div>
              {% elif trash.projectName %}
                <div class="btn btn-outline-danger btn-sm" hx-delete={% url 'timesheet:Full_Delete_Project' id=trash.id %}>{% trans "Delete" %}</div>
              {% else %}
                <div class="btn btn-outline-danger btn-sm" hx-delete={% url 'timesheet:Full_Delete_Timesheet' id=trash.id %}>{% trans "Delete" %}</div>
              {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
    <!--Pagination-->
      {% if pgx.pgs > 1 %}
      <nav aria-label="Page navigation" class="m-3">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="/user_trash/{{pgx.idxpl}}/{{pgx.idxpr}}/" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% for link in pgx.lks %}
          <li class="page-item"><a class="page-link" id="page-link" href="/user_trash/{{link.pl}}/{{link.pr}}/">{{link.page}}</a></li>
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="/user_trash/{{pgx.idxnl}}/{{pgx.idxnr}}/" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
      {% endif %}

    {% else %}
        <p>{% trans "Trash is empty." %}</p>
    {% endif %}
    </div>
</div>
{% endblock %}