mateapptimesheet/main/urls.py
from django.urls import path, include
from . import views
from timesheet.views import create_self_timesheet, self_timesheets

app_name = 'main'

urlpatterns = [
    path('', self_timesheets, name = 'Self_Timesheet'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('search/', views.search, name='Search'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapptimesheet/timesheet/urls.py
from django.urls import path, include, reverse
from . import views

app_name = 'timesheet'

# Customers

urlpatterns = [
    path('create_company/', views.create_company, name='Create_Company'),
    path('edit_company/<int:id>/', views.edit_company, name='Edit_Company'),
    path('delete_company/<int:id>/', views.delete_company, name='Delete_Company'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='Restore_Company'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='Full_Delete_Company'),
    path('companies/<int:a>/<int:b>/', views.companies , name='Companies'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company , name='Company'),
    path('company_notes/<int:id>/', views.companyNotes, name='Company_Notes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='Company_Notes_Title'),
    path('company_edit_notes/<int:id>/', views.companyNotesEdit, name='Company_Edit_Notes'),
]

# Projects

urlpatterns += [
    path('create_project/', views.create_project, name='Create_Project'),
    path('edit_project/<int:id>/', views.edit_project, name='Edit_Project'),
    path('delete_project/<int:id>/', views.delete_project, name='Delete_Project'),
    path('restore_project/<int:id>/<int:u>/', views.restore_project, name='Restore_Project'),
    path('full_delete_project/<int:id>/', views.full_delete_project, name='Full_Delete_Project'),
    path('projects/<int:a>/<int:b>/', views.projects , name='Projects'),
    path('project/<int:id>/<int:a>/<int:b>/', views.project , name='Project'),
    path('project_notes/<int:id>/', views.projectNotes, name='Project_Notes'),
    path('project_notes_title/<int:id>/', views.projectNotesTitle, name='Project_Notes_Title'),
    path('project_edit_notes/<int:id>/', views.projectNotesEdit, name='Project_Edit_Notes'),
]

# Timesheet

urlpatterns += [
    path('create_timesheet/', views.create_timesheet, name='Create_Timesheet'),
    path('create_self_timesheet/', views.create_self_timesheet, name='Create_Self_Timesheet'),
    path('edit_timesheet/<int:id>/', views.edit_timesheet, name='Edit_Timesheet'),
    path('edit_self_timesheet/<int:id>/', views.edit_self_timesheet, name='Edit_Self_Timesheet'),
    path('delete_timesheet_table/<int:id>/<int:u>/', views.delete_timesheet_table, name='Delete_Timesheet_Table'),
    path('delete_timesheet/<int:id>/<int:u>/', views.delete_timesheet, name='Delete_Timesheet'),
    path('restore_timesheet/<int:id>/<int:u>/', views.restore_timesheet, name='Restore_Timesheet'),
    path('full_delete_timesheet/<int:id>/', views.full_delete_timesheet, name='Full_Delete_Timesheet'),
    path('timesheets/<int:a>/<int:b>/', views.timesheets , name='Timesheets'),
    path('timesheets_self/<int:a>/<int:b>/', views.self_timesheets , name='Self_Timesheets'),
    path('timesheet/<int:id>/', views.timesheet , name='Timesheet'),
    path('timesheet_self/<int:id>/', views.timesheet_self , name='Timesheet_Self'),
    path('timesheet_notes/<int:id>/', views.timeNotes, name='Timesheet_Notes'),
    path('timesheet_notes_title/<int:id>/', views.timeNotesTitle, name='Timesheet_Notes_Title'),
    path('timesheet_edit_notes/<int:id>/', views.timeNotesEdit, name='Timesheet_Edit_Notes'),
]

# Users

urlpatterns += [
    path('users/<int:a>/<int:b>/', views.users, name='Users'),
    path('user/<int:id>/<int:a>/<int:b>/', views.user_detail, name='User'),
]


# urlpatterns += [
#     path('dev', views.dev_button, name='Dev'),
# ]

mateapptimesheet/timesheet/models.py
from datetime import date
from django.db import models
from django.conf import settings
from .validators import invalidate_future_timesheets

# Create your models here.

class BaseModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True

class Address(BaseModel):
    street = models.CharField(max_length=200, blank=True)
    postalCode = models.CharField(max_length=7, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.street}, {self.city}'

class Company(BaseModel):
    companyName = models.CharField(max_length=100, blank=True)
    tax_id = models.CharField(max_length=15, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True)
    companyPhone = models.CharField(max_length=25, blank=True)
    companyNotes = models.CharField(max_length=2000, blank=True)
    companyNotesTitle = models.CharField(max_length=200, blank=True, null=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)

    def title(self):
        title = self.companyNotes.split('\n', 1)[0]
        return title

    def save(self, *args, **kwargs):
        self.companyNotesTitle = self.title()
        super(Company, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.companyName

class Project(BaseModel):
    projectName = models.CharField(max_length=100, blank=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)
    projectStatus = models.BooleanField(blank=True, default=1)
    projectType = models.CharField(max_length=15, blank=True)
    budget = models.IntegerField(default=0, blank=True)
    startDate = models.DateField(blank=False, null=True, default=date.today)
    projectAge = models.IntegerField(default=0, blank=True)
    projectNotes = models.CharField(max_length=2000, blank=True)
    projectNotesTitle = models.CharField(max_length=200, blank=True, null=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)

    def title(self):
        fline = self.post.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.projectNotesTitle = self.title()
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.projectName} - {self.company}'
    
class Time(BaseModel):
    timeItem = models.IntegerField(blank=False, null=True)
    timeDate = models.DateField(blank=False, null=True, default=date.today, validators=[invalidate_future_timesheets])
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, blank=True, null=True)
    timeType = models.CharField(max_length=100, blank=True)
    timeRevenue = models.BooleanField(blank=True, default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, blank=True, null=True)
    timeNotes = models.CharField(max_length=2000, blank=True)
    timeNotesTitle = models.CharField(max_length=200, blank=True, null=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)

    def title(self):
        fline = self.post.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.timeNotesTitle = self.title()
        super(Time, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.timeDate}, {self.project}, {self.user}'

mateapptimesheet/timesheet/forms.py
from django import forms
from .models import Company, Project, Time
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.forms.widgets import SelectDateWidget

TYPE_CHOICES = [
    ("Business", _("Business Hours")),
    ("Non Business", _("Non Business Hours")),
]

FILTER_CHOICES = [
    (None, _("Select Filter")),
    ("Current_Month", _("Current Month")),
    ("Last_Month", _("Last Month")),
    ("Last_Trimester", _("Last Quarter")),
    ("Last_Semester", _("Last Semester")),
    ("Last_Year", _("Last Year")),
    ("All", _("All")),
]

HOUR_CHOICES = [
    (1, "1 Hs."),
    (2, "2 Hs."),
    (3, "3 Hs."),
    (4, "4 Hs."),
    (5, "5 Hs."),
    (6, "6 Hs."),
    (7, "7 Hs."),
    (8, "8 Hs."),
    (9, "9 Hs."),
    (10, "10 Hs."),
    (11, "11 Hs."),
    (12, "12 Hs."),
]

PROJECT_TYPE_CHOICES = [
    ("onetime", _("One-Time")),
    ("recurrent", _("Recurrent")),
]

PROJECT_STATUS_CHOICES = [
    (1, _("Active")),
    (0, _("Finished")),
]


class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = [
            'companyName',
            'tax_id',
            'companyNotes'
        ]

        widgets = {
            'companyName': forms.TextInput(attrs={'class':'form-control','required':'True','placeholder':'Customer Name'}),
            'tax_id': forms.TextInput(attrs={'class':'form-control','placeholder':'Tax ID'}),
            'companyNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }  

class ProjectForm(forms.ModelForm):

    projectStatus = forms.ChoiceField(
        choices=PROJECT_STATUS_CHOICES
    )
    projectType = forms.ChoiceField(
        choices=PROJECT_TYPE_CHOICES
    )

    projectStatus.widget.attrs.update({'class': 'form-select'})
    projectType.widget.attrs.update({'class': 'form-select'})

    class Meta:
        model = Project
        fields = [
            'projectName',
            'company',
            'projectStatus',
            'projectType',
            'startDate',
            'budget',
            'projectNotes',
        ]
    
        widgets = {
            'projectName': forms.TextInput(attrs={'class':'form-control','required':'True','placeholder':'Project Name'}),
            'company': forms.Select(attrs={'class':'form-select','required':'True'}),
            'startDate' : forms.DateInput(attrs={'type':'date', 'class':'form-control', 'required':'True'}),
            'budget' : forms.NumberInput(attrs={'class':'form-control'}),
            'projectNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }
    
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(deleted=False).order_by('companyName')
        self.fields['company'].empty_label = _("Select Customer:")

class TimesheetForm(forms.ModelForm):

    timeType = forms.ChoiceField(
        choices=TYPE_CHOICES
    )
    timeItem = forms.ChoiceField(
        choices=HOUR_CHOICES
    )

    timeType.widget.attrs.update({'class': 'form-select'})
    timeItem.widget.attrs.update({'class': 'form-select'})

    class Meta:
        model = Time

        fields = [
            'timeItem',
            'timeDate',
            'project',
            'timeType',
            'timeNotes',
            'user',
        ]

        widgets = {
            # 'timeDate': forms.DateInput(attrs={'class':'form-control','required':'True',}),
            'timeDate': forms.DateInput(attrs={'type':'date', 'class':'form-control', 'required':'True'}),
            'project': forms.Select(attrs={'class':'form-select','required':'True',}),
            'timeNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
            'user': forms.Select(attrs={'class':'form-select','required':'True'})
        }

    def __init__(self, *args, **kwargs):
        super(TimesheetForm, self).__init__(*args, **kwargs)
        
        self.fields['project'].queryset = Project.objects.filter(deleted=False).order_by('projectName')
        self.fields['project'].empty_label = _("Select Project:")

        self.fields['user'].queryset = get_user_model().objects.order_by('last_name').exclude(is_superuser=True)
        self.fields['user'].empty_label = _("Select User")

class FilterForm(forms.Form):

    f = forms.ChoiceField(
        choices=FILTER_CHOICES,
        required=False,
    )
    f.widget.attrs.update({'class': 'form-select f'})

    q = forms.CharField(
        label="Search",
        required=False,
        widget=forms.TextInput(attrs={'class':'form-control me-2 q', 'placeholder':_('Search:'), 'type':'search', 'aria-label':'search'}),
    )

class CompanyNotesForm(forms.ModelForm):
    '''Short form for partial edit with htmx'''

    class Meta:
        model = Company
        fields = {
            'companyNotes',
        }

        widgets = {
            'companyNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

class ProjectNotesForm(forms.ModelForm):
    '''Short form for partial edit with htmx'''

    class Meta:
        model = Project
        fields = {
            'projectNotes',
        }

        widgets = {
            'projectNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

class TimeNotesForm(forms.ModelForm):
    '''Short form for partial edit with htmx'''

    class Meta:
        model = Time
        fields = {
            'timeNotes',
        }

        widgets = {
            'timeNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

mateapptimesheet/templates/timesheet/project_view.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}


<div class="row mx-1 justify-content-center">
  <div class="col bg-white p-3 mx-1 px-5 col-lg-10 rounded border ">
    <h3>{{project.projectName}}</h3>
    <a class="nav-link" href={% url 'timesheet:Company' id=project.company.id a=0 b=5 %}><h6>{{project.company}}</h6></a>
    <hr class="separator">

    <div class="row row-col-2 py-2 justify-content-center">
      <div class="col col-10 col-md-6 py-1 my-2">
        
        <h6>{% trans "Start Date: " %}{{ project.startDate }}</h6>

        {% if project.projectType == 'onetime' %}
        <h6>{% trans "Type: One-Time" %}</h6>
        {% else %}
        <h6>{% trans "Type: Recurrent" %}</h6>
        {% endif %}

        {% if project.projectStatus %}
        <h6>{% trans "Status: Active" %}</h6>
        {% else %}
        <h6>{% trans "Status: Finished" %}</h6>
        {% endif %}
      </div>
      <div class="col col-10 col-md-6 py-1 light-border">
        {% if recurrent %}
        <h5>{% trans "Monthly Budget: " %}{{ project.budget }} hs.</h5>
        <h6>{% trans "Current month remaining: " %}{{ pending_time }} hs.</h6>
        {% else %}
        <h5>{% trans "Budget: " %}{{ project.budget }} hs.</h5>
        <h6>{% trans "Pending: " %}{{ pending_time }} hs.</h6>
        {% endif %}
      </div>
    </div>

    <div>
      {% include 'timesheet/partials/project_notes_title.html' %}
    </div>


    {% if user.role == 'Supervisor' or user.role == 'Administrator' %}
    <div class="row mx-1 justify-content-center">
        <div class="col col-lg-10 d-flex justify-content-center">       
            <p><a href={% url 'timesheet:Edit_Project' id=project.id %} class="btn btn-outline-success mt-2 px-4 mx-3" role="button">{% trans "Edit" %}</a></p>
            <p><a href={% url 'timesheet:Projects' a=0 b=10 %} class="btn btn-outline-secondary mt-2 px-3 mx-3" role="button">{% trans "Projects" %}</a></p>
            {% if empty %}
            <p><a href={% url 'timesheet:Delete_Project' id=project.id %} class="btn btn-outline-danger mt-2 mx-3" role="button">{% trans "Delete" %}</a></p>
            {% endif %}
        </div>
    </div>
    {% endif %}

  </div>
</div>

<div class="row mt-3 mx-1 justify-content-center">
    <div class="col bg-white p-3 border rounded col-lg-10">
      <!-- Table Block Header -->
      <nav class="navbar navbar-expand-lg table_nav">
        <div class="container-fluid">
          <a class="navbar-brand" href=""><h4>{% trans "Resources" %}</h4></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#timesheetsNavbar" aria-controls="timesheetsNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Offcanvas Header -->
          <div class="offcanvas offcanvas-end " tabindex="-1" id="timesheetsNavbar" aria-labelledby="offcanvasTimesheetsLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasTimesheetsLabel">{% trans "Resources" %}</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>

            <!-- Incanvas Form -->
            <div class="d-none d-lg-block">
              <div class="collapse navbar-collapse" id="timesheetsNavbar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                </ul>
                <form class="d-flex btn-sm" role="search" id="qform">
                  {{filterform.q}}
                  {{filterform.f}}
                <button class="btn btn-outline-success mx-2" type="submit">{% trans "Filter" %}</button>
              </form>
                <div>
                  <a href="{% url 'timesheet:Project' id=project.id a=0 b=5 %}" class="btn btn-outline-secondary my-2">{% trans "Clear" %}</a>
                </div>
              </div>
            </div>

            <!-- Offcanvas Form -->
            <div class="d-lg-none">
              <div class="offcanvas-body">
                <form class="col btn-sm" role="search" id="qform">
                  <div class="my-2">{{filterform.q}}</div>
                  <div class="my-2">{{filterform.f}}</div>
                  <button class="btn btn-outline-success mr-2" type="submit">{% trans "Filter" %}</button>
                  <a href="{% url 'timesheet:Project' id=project.id a=0 b=5 %}" class="btn btn-outline-secondary my-2">{% trans "Clear" %}</a>
                </form>
              </div>
            </div>

          </div>
        </div>
      </nav>
    {% if user_list %}
    <div class="table-responsive">
    <table class="table table-hover" id="timesheet_list" name="timesheet_List">
        <!-- Cabecera de Tabla -->
        <thead class="table-success">
            <th class="px-3">{% trans "Name" %}</th>
            <th class="text-center d-none d-sm-block">{% trans "Allocated" %}&nbsp;&Sigma;:&nbsp;{{ total_alloc_time.alloc_time__sum }} hs.</th>
            <th class="text-center d-block d-sm-none">&nbsp;&Sigma;:&nbsp;{{ total_alloc_time.alloc_time__sum }} hs.</th>
        </thead>

        <!-- Cuerpo de Tabla -->

        {% if user.role == 'Supervisor' or user.role == 'Administrator' %}

        <tbody>
            {% for Users in user_list %}
            <tr>
                <td class="px-3"><a class="nav-link" href={% url 'timesheet:User' id=Users.id a=0 b=10 %}>{{ Users.last_name }}, {{ Users.first_name}}</a></td>
                <td class="text-center">{{ Users.alloc_time }} hs.</td>
            </tr>
            {% endfor %}
        </tbody>

        {% else %}

        <tbody>
          {% for Users in user_list %}
            <tr>
              <td class="px-3">{{ Users.last_name }}, {{ Users.first_name}}</td>
              <td class="text-center">{{ Users.alloc_time }} hs.</td>
            </tr>

          {% endfor %}

        {% endif %}

    </table>
    </div>
    {% if pgx.pgs > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="/timesheet/project/{{project.id}}/{{pgx.idxpl}}/{{pgx.idxpr}}/" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% for link in pgx.lks %}
          <li class="page-item"><a class="page-link" id="page-link" href="/timesheet/project/{{project.id}}/{{link.pl}}/{{link.pr}}/">{{link.page}}</a></li>
          {% endfor %}
          <li class="page-item">
            <a class="page-link" href="/timesheet/project/{{project.id}}/{{pgx.idxnl}}/{{pgx.idxnr}}/" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    {% endif %}
    {% else %}
    <div class='mx-5 my-3'>{% trans "No timesheets available." %}</div>
    {% endif %}
    </div>
</div>

<script src="{% static 'timesheet/js/project_view_helper.js' %}"></script>

{% endblock %}

mateapptimesheet/templates/timesheet/timesheet_view.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<div class="row py-3 justify-content-center">
    <div class="col bg-white p-3 mx-1 px-5 col-lg-10 rounded border ">
        <h3>{{timesheet.timeDate}}</h3>
        <hr class="separator">

        <div class="row row-col-2 py-3 justify-content-start">
            <div class="col col-10 col-md-6 py-1 my-2">
                <div class="ps-1">
                    <h5>{% trans "User: " %}{{timesheet.user}}</h5>
                    <h5>{% trans "Time: " %}<b>{{timesheet.timeItem}} Hs.</b></h5>
                    <h5>{% trans "Project: " %} <a class='text-reset text-decoration-none link-success' href={% url 'timesheet:Project' id=timesheet.project.id a=0 b=5%}>{{timesheet.project.projectName}}</a></h5>
                </div>
            </div>

            <div class="col col-10 col-md-6 py-1 light-border">
                <h5>{% trans "Customer: " %} <a class='text-reset text-decoration-none link-success' href={% url 'timesheet:Company' id=timesheet.project.company.id a=0 b=5%}>{{timesheet.project.company}}</a></h5>
                {% if timesheet.timeType == "Business" %}
                <h5>{% trans "Type: Business Hours" %}</h5>
                {% else %}
                <h5>{% trans "Type: Non Business Hours" %}</h5>
                {% endif %}
            </div>
        </div>

        <div>
            {% include 'timesheet/partials/timesheet_notes_title.html' %}
        </div>

        <div class="row py-3 mx-1 justify-content-center">
            <div class="col col-lg-10 d-flex justify-content-center">       
                <p><a href={% url 'timesheet:Edit_Timesheet' id=timesheet.id %} class="btn btn-outline-success mt-2 px-4 mx-2" role="button">{% trans "Edit" %}</a></p>
                <p><a href={% url 'timesheet:Timesheets' a=0 b=10 %} class="btn btn-outline-secondary mt-2 px-3 mx-2" role="button">{% trans "Timesheets" %}</a></p>
                <p><a href={% url 'timesheet:Delete_Timesheet' id=timesheet.id u=1%} class="btn btn-outline-danger mt-2 mx-2" role="button">{% trans "Delete" %}</a></p>
            </div>
        </div>
        
    </div>
</div>

{% endblock %}

mateapptimesheet/templates/timesheet/timesheet_view_self.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<div class="row py-3 justify-content-center">
    <div class="col bg-white p-3 mx-1 px-5 col-lg-10 rounded border ">
        <h3>{{timesheet.timeDate}}</h3>
        <hr class="separator">

        <div class="row row-col-2 py-3 justify-content-start">
            <div class="col col-10 col-md-6 py-1 my-2">
                <div class="ps-1">
                    <h5>{% trans "Time: " %}<b>{{timesheet.timeItem}} Hs.</b></h5>
                    <h5>{% trans "Project: " %}{{timesheet.project.projectName}}</h5>
                </div>
            </div>
            <div class="col col-10 col-md-6 py-1 light-border">
                <h5 class="mt-2">{% trans "Customer: " %}{{timesheet.project.company}}</h5>
                {% if timesheet.timeType == "Business" %}
                    <h5>{% trans "Type: Business Hours" %}</h5>
                {% else %}
                    <h5>{% trans "Type: Non Business Hours" %}</h5>
                {% endif %}
            </div>
        </div>
       
        <div>
            {% include 'timesheet/partials/timesheet_notes_title.html' %}
        </div>


        <div class="row py-3 mx-1 justify-content-center">
            <div class="col col-lg-10 d-flex justify-content-center">       
                <p><a href={% url 'timesheet:Edit_Self_Timesheet' id=timesheet.id %} class="btn btn-outline-success mt-2 px-4 mx-2" role="button">{% trans "Edit" %}</a></p>
                <p><a href={% url 'timesheet:Self_Timesheets' a=0 b=10 %} class="btn btn-outline-secondary mt-2 px-3 mx-2" role="button">{% trans "Timesheets" %}</a></p>
                <p><a href={% url 'timesheet:Delete_Timesheet' id=timesheet.id u=0%} class="btn btn-outline-danger mt-2 mx-2" role="button">{% trans "Delete" %}</a></p>
            </div>
        </div>
    </div>
</div>



{% endblock %}