mateapptimesheet/main/urls.py
from django.urls import path, include
from . import views
from timesheet.views import create_self_timesheet, self_timesheets

app_name = 'main'

urlpatterns = [
    path('', self_timesheets, name = 'Self_Timesheet'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('search/', views.search, name='Search'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapptimesheet/timesheet/urls.py
from django.urls import path, include, reverse
from . import views

app_name = 'timesheet'

# Customers

urlpatterns = [
    path('create_company/', views.create_company, name='Create_Company'),
    path('edit_company/<int:id>/', views.edit_company, name='Edit_Company'),
    path('delete_company/<int:id>/', views.delete_company, name='Delete_Company'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='Restore_Company'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='Full_Delete_Company'),
    path('companies/<int:a>/<int:b>/', views.companies , name='Companies'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company , name='Company'),
    path('company_notes/<int:id>/', views.companyNotes, name='Company_Notes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='Company_Notes_Title'),
    path('company_edit_notes/<int:id>/', views.companyNotesEdit, name='Company_Edit_Notes'),
]

# Projects

urlpatterns += [
    path('create_project/', views.create_project, name='Create_Project'),
    path('edit_project/<int:id>/', views.edit_project, name='Edit_Project'),
    path('delete_project/<int:id>/', views.delete_project, name='Delete_Project'),
    path('restore_project/<int:id>/<int:u>/', views.restore_project, name='Restore_Project'),
    path('full_delete_project/<int:id>/', views.full_delete_project, name='Full_Delete_Project'),
    path('projects/<int:a>/<int:b>/', views.projects , name='Projects'),
    path('project/<int:id>/<int:a>/<int:b>/', views.project , name='Project'),
    path('project_notes/<int:id>/', views.projectNotes, name='Project_Notes'),
    path('project_notes_title/<int:id>/', views.projectNotesTitle, name='Project_Notes_Title'),
    path('project_edit_notes/<int:id>/', views.projectNotesEdit, name='Project_Edit_Notes'),
]

# Timesheet

urlpatterns += [
    path('create_timesheet/', views.create_timesheet, name='Create_Timesheet'),
    path('create_self_timesheet/', views.create_self_timesheet, name='Create_Self_Timesheet'),
    path('edit_timesheet/<int:id>/', views.edit_timesheet, name='Edit_Timesheet'),
    path('edit_self_timesheet/<int:id>/', views.edit_self_timesheet, name='Edit_Self_Timesheet'),
    path('delete_timesheet_table/<int:id>/<int:u>/', views.delete_timesheet_table, name='Delete_Timesheet_Table'),
    path('delete_timesheet/<int:id>/<int:u>/', views.delete_timesheet, name='Delete_Timesheet'),
    path('restore_timesheet/<int:id>/<int:u>/', views.restore_timesheet, name='Restore_Timesheet'),
    path('full_delete_timesheet/<int:id>/', views.full_delete_timesheet, name='Full_Delete_Timesheet'),
    path('timesheets/<int:a>/<int:b>/', views.timesheets , name='Timesheets'),
    path('timesheets_self/<int:a>/<int:b>/', views.self_timesheets , name='Self_Timesheets'),
    path('timesheet/<int:id>/', views.timesheet , name='Timesheet'),
    path('timesheet_self/<int:id>/', views.timesheet_self , name='Timesheet_Self'),
    path('timesheet_notes/<int:id>/', views.timeNotes, name='Timesheet_Notes'),
    path('timesheet_notes_title/<int:id>/', views.timeNotesTitle, name='Timesheet_Notes_Title'),
    path('timesheet_edit_notes/<int:id>/', views.timeNotesEdit, name='Timesheet_Edit_Notes'),
]

# Users

urlpatterns += [
    path('users/<int:a>/<int:b>/', views.users, name='Users'),
    path('user/<int:id>/<int:a>/<int:b>/', views.user_detail, name='User'),
]


# urlpatterns += [
#     path('dev', views.dev_button, name='Dev'),
# ]

mateapptimesheet/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name = 'Register'),
    path('profile/', views.profileView , name = 'profileView'),
    path('change_password/', views.passwordChange, name = 'passwordChange'),
    path('profile_edit/', views.profileEdit , name = 'profileEdit'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password_reset/', views.passwordResetRequest, name = 'passwordReset'),
    path('password_reset_confirm/<uidb64>/<token>/', views.passwordResetConfirm, name='passwordResetConfirm'),
    path('users/<int:a>/<int:b>/', views.users, name = 'Users'),
    path('deleted_users/<int:a>/<int:b>/', views.users_deleted, name = 'deletedUsers'),
    path('user/<int:id>/', views.user, name='User'),
    path('create_user/', views.create_user, name = 'createUser'),
    path('edit_user/<int:id>', views.edit_user, name = 'editUser'),
]

mateapptimesheet/templates/includes/admin_navbar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-secondary-subtle">
    <div class="container-fluid px-4">
      <a class="navbar-brand" href="/">
      <img src="{% static 'main/images/mate_plain.svg' %}" alt="MateApp" height="36">
    </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#mainNavbar" aria-controls="mainNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end bg-secondary-subtle" tabindex="-1" id="mainNavbar" aria-labelledby="offcanvasNavbarLabel">

        <div class="offcanvas-header">
          <h5 class="offcanvas-title text-secondary-emphasis" id="offcanvasNavbarLabel"><img src="{% static 'main/images/mate_plain.svg' %}" alt="MateApp" height="36">&nbsp;&nbsp;{% trans "Administration" %}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
            {% if user.role == 'Administrator' %}
            <div class="dropdown-container">
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><h5 class="text-secondary-emphasis"><i class="bi bi-people"></i>&nbsp;{% trans "Users" %}</h5></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href={% url 'users:Users' a=0 b=10 %}><i class="bi bi-people"></i>&nbsp;{% trans "Users" %}</a></li>
                <li><a class="dropdown-item" href={% url 'users:deletedUsers' a=0 b=10 %}><i class="bi bi-person-slash"></i>&nbsp;{% trans "Inactive Users" %}</a></li>
                <li><a class="dropdown-item" href={% url 'users:createUser' %}><i class="bi bi-plus-square"></i>&nbsp;{% trans "Create User" %}</a></li>
              </ul>  
            </li>
            </div>
            <div class="dropdown-container">
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><h5 class="text-secondary-emphasis"><i class="bi bi-hdd-stack"></i>&nbsp;{% trans "Backup" %}</h5></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href={% url 'main:Admin_Home' a=0 b=10 %}><i class="bi bi-hdd-stack"></i>&nbsp;{% trans "Backups" %}</a></li>
                <li><a class="dropdown-item" href="/backup/"><i class="bi bi-plus-square"></i>&nbsp;{% trans "New Backup" %}</a></li>
              </ul>  
            </li>
            </div>
            <li class="nav-item">
              <a class="nav-link" href={% url 'main:Admin_Trash' a=0 b=10 %}><h5 class="text-secondary-emphasis"><i class="bi bi-trash"></i>&nbsp;{% trans "System Trash" %}</h5></a>
            </li>
            {% endif %}
          </ul>
          <div class="d-none d-lg-block">
            <ul class="navbar-nav mx-4 ms-auto mb-2 mb-lg-0">

              {% if user.role == 'Administrator' %}
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/" data-bs-toggle="tooltip" data-bs-title={% trans "Home" %} data-bs-placement="bottom">
                  <img src="{% static 'main/images/home.svg' %}" alt="Admin">
                </a>
              </li>     
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/signout/" data-bs-toggle="tooltip" data-bs-title={% trans "Logout" %} data-bs-placement="bottom">
                  <img src="{% static 'main/images/logout.svg' %}" alt="Logout">
                </a>
              </li>
              {% endif %}
      
            </ul>
          </div>
          <div class="d-lg-none">
            <ul class="navbar-nav mx-4 ms-auto mb-2 mb-lg-0">
              {% if user.role == 'Administrator' %}
              <li class="nav-item">
                <a class="nav-link" href="/">
                  <h5><i class="bi bi-house"></i>&nbsp; {% trans "Home" %}</h5>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signout/">
                  <h5><i class="bi bi-box-arrow-right"></i>&nbsp;{% trans "Logout" %}</h5>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>

mateapptimesheet/templates/includes/footer.html
<div class="my-5">&nbsp;</div>

mateapptimesheet/templates/includes/messaging.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message|safe|escape }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                {{ message|safe|escape }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                {{ message|safe|escape }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

mateapptimesheet/templates/includes/navbar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-success-subtle">
    <div class="container-fluid px-4">
      <a class="navbar-brand" href="/#">
      <img src="{% static 'main/images/mate_plain.svg' %}" alt="MateApp" height="36">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#mainNavbar" aria-controls="mainNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end bg-success-subtle" tabindex="-1" id="mainNavbar" aria-labelledby="offcanvasNavbarLabel">

        <div class="offcanvas-header">
          <h5 class="offcanvas-title text-success-emphasis" id="offcanvasNavbarLabel"><img src="{% static 'main/images/mate_plain.svg' %}" alt="MateApp" height="36">&nbsp;&nbsp;MateApp</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href={% url 'timesheet:Self_Timesheets' a=0 b=10 %}><h5 class="text-success-emphasis"><i class="bi bi-view-list"></i>&nbsp;{% trans "My Timesheets" %}</h5></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'timesheet:Create_Self_Timesheet'%}><h5 class="text-success-emphasis"><i class="bi bi-plus-square"></i>&nbsp;{% trans "Log Timesheet" %}</h5></a>
            </li>
            {% if user.role == 'Supervisor' or user.role == 'Administrator' %}
            <div class="dropdown-container">
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><h5 class="text-success-emphasis"><i class="bi bi-kanban"></i>&nbsp;{% trans "Management" %}</h5></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><a class="dropdown-item" href={% url 'timesheet:Users' a=0 b=10 %}><i class="bi bi-people"></i>&nbsp;{% trans "Resources" %}</a></li>
                <li><a class="dropdown-item" href={% url 'timesheet:Projects' a=0 b=10 %}><i class="bi bi-code-square"></i>&nbsp;{% trans "Projects" %}</a></li>
                <li><a class="dropdown-item" href={% url 'timesheet:Companies' a=0 b=10 %}><i class="bi bi-buildings"></i>&nbsp;{% trans "Customers" %}</a></li>
                <li><a class="dropdown-item" href={% url 'timesheet:Timesheets' a=0 b=10 %}><i class="bi bi-clock-history"></i>&nbsp;{% trans "Timesheets" %}</a></li>
              </ul>  
            </li>
          </div>
            {% endif %}
            {% endif %}

          </ul>
          <div class="d-none d-lg-block">
            <ul class="navbar-nav mx-4 ms-auto mb-2 mb-lg-0">

              {% if user.is_authenticated %}
                {% comment %} <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/" data-bs-toggle="tooltip" data-bs-title={% trans "Search" %} data-bs-placement="bottom">
                    <img src="{% static 'main/images/search.svg' %}" alt="Search">
                  </a>
                </li> {% endcomment %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/user_trash/0/10" data-bs-toggle="tooltip" data-bs-title={% trans "Trash" %} data-bs-placement="bottom">
                    <img src="{% static 'main/images/trash.svg' %}" alt="Trash">
                  </a>
                </li>
              {% if user.role == 'Administrator' %}
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/admin_home/0/10/" data-bs-toggle="tooltip" data-bs-title={% trans "Admin" %} data-bs-placement="bottom">
                  <img src="{% static 'users/images/braces.svg' %}" alt="Admin">
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/users/profile/" data-bs-toggle="tooltip" data-bs-title={% trans "Profile" %} data-bs-placement="bottom">
                  <img src="{% static 'users/images/person.svg' %}" alt="Profile">
                </a>
            
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/signout/" data-bs-toggle="tooltip" data-bs-title={% trans "Logout" %} data-bs-placement="bottom">
                  <img src="{% static 'main/images/logout.svg' %}" alt="Logout">
                </a>
              </li>

              {% else %}

                {% if REGISTRATION_SELF_ENABLE and not registerform %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/users/register"><h5>{% trans "Register" %}  
                    <img src="{% static 'users/images/register.svg' %}" alt="Register"></h5>
                  </a>
                </li>
                {% endif %}

              {% endif %}
      
            </ul>
          </div>
          <div class="d-lg-none">
            <ul class="navbar-nav mx-4 ms-auto mb-2 mb-lg-0">

              {% if user.is_authenticated %}
                {% comment %} <li class="nav-item">
                  <a class="nav-link" href="/">
                    <h5><i class="bi bi-search"></i>&nbsp;{% trans "Search" %}</h5>
                  </a>
                </li> {% endcomment %}
                <li class="nav-item">
                  <a class="nav-link" href="/user_trash/0/10">
                    <h5><i class="bi bi-trash"></i>&nbsp;{% trans "Trash" %}</h5>
                  </a>
                </li>
              {% if user.role == 'Administrator' %}
              <li class="nav-item">
                <a class="nav-link" href="/admin_home/0/10/">
                  <h5><i class="bi bi-braces"></i>&nbsp; {% trans "Administration" %}</h5>
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="/users/profile/">
                  <h5><i class="bi bi-person"></i>&nbsp; {% trans "Profile" %}</h5>
                </a>
            
              <li class="nav-item">
                <a class="nav-link" href="/signout/">
                  <h5><i class="bi bi-box-arrow-right"></i>&nbsp;{% trans "Logout" %}</h5>
                </a>
              </li>

              {% else %}

                {% if REGISTRATION_SELF_ENABLE and not registerform %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="/users/register"><h5>{% trans "Register" %}  
                    <img src="{% static 'users/images/register.svg' %}" alt="Register"></h5>
                  </a>
                </li>
                {% endif %}

              {% endif %}
      
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>